spring:
  application:
    name: afisha

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8080

stats-service:
  server:
    url: http://${STATS_HOST}:9090

