spring:
  application:
    name: afisha

  datasource:
    url: jdbc:postgresql://localhost:5432/afisha
    username: postgres
    password: 1234
  jpa:
    show-sql: true


server:
  port: 8080

stats-service:
  server:
    url: http://localhost:9090

