CREATE TABLE IF NOT EXISTS hits (
    id SERIAL PRIMARY KEY,
    app VARCHAR(50) NOT NULL,
    uri VARCHAR(100) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
)